export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const LIST_APPLICATIONS = "LIST_APPLICATIONS";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";
